package com.ebridgecommerce.domain;

/**
*
* @author DaTekeshe
*/
public enum TxnType {
   COS_QUERY, COS_CHANGE, BALANCE_TRANSFER, VOUCHER_RECHARGE, DATA_BUNDLE_PURCHASE, REDEEM_USAGE_BONUS, CONFIRM_FRIEND, MODIFY_FRIEND, CONFIRM_BONUS_COLLECTION
}
